import { PayloadAction, createSlice } from '@reduxjs/toolkit'
import { fetchMoviesAsync } from './movieThunk'

// PayloadAction is a type for defining actions with a payload
// createSlice is a function used to create Redux slices

export interface Movie {
    _id: string
    id: string
    primaryImage: {
        id: string
        width: number
        height: number
        url: string
        caption: {
            plainText: string
            __typename: string
        }
        __typename: string
    }
    titleType: {
        text: string
        id: string
        isSeries: boolean
        isEpisode: boolean
        __typename: string
    }
    titleText: {
        text: string
        __typename: string
    }
    originalTitleText: {
        text: string
        __typename: string
    }
    releaseYear: {
        year: number
        endYear: null | number
        __typename: string
        releaseDate: null | number
    }
}

interface MovieState {
    movies: Movie[]
    filteredMovies: Movie[]
    loading: boolean
}

const initialState: MovieState = {
    movies: [],
    filteredMovies: [],
    loading: true,
}
// using the createSlice function to create a Redux slice named 'movie'
export const MovieSlice = createSlice({
    name: 'movie',
    initialState, // it takes an initialState and an object containing reducers
    reducers: {
        setLoading: (state, action: PayloadAction<{ loading: boolean }>) => {
            state.loading = action.payload.loading
        },
        searchMovies: (
            state,
            action: PayloadAction<{ searchQuery: string }>
        ) => {
            const searchQuery = action.payload.searchQuery.toLowerCase()

            state.filteredMovies = state.movies.filter((movie) =>
                movie.titleText.text.toLowerCase().includes(searchQuery)
            )
        },
    },
    extraReducers: (builder) => {
        builder.addCase(fetchMoviesAsync.fulfilled, (state, action) => {
            state.movies = action.payload
            state.loading = false
        })
    },
})
export const selectFilteredMovies = (state: MovieState) => state.filteredMovies
export const selectLoading = (state: MovieState) => state.loading

export default MovieSlice.reducer
// The reducer is used to update the state in the Redux store
// In Redux Toolkit's createSlice function, the property is called reducers (plural),
// but when you access the generated reducer from the resulting slice, it is named reducer s(singular)
export const { setLoading, searchMovies } = MovieSlice.actions
// and the action creator is used to dispatch the addMovies action

// this line of code is using destructuring to extract the addMovies action creator from the actions object
// of MovieSlice. The actions object is automatically generated by createSlice based on the defined reducers

// if I had multiple reducers in the reducers property, the actions object would have multiple properties,
// each corresponding to a reducer name.destructing them would look like this:
// const { addMovies, anotherReducerAction, yetAnotherReducerAction } = MovieSlice.actions;
